# Generated by Django 4.0.5 on 2022-07-14 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_answer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Questions',
            new_name='Question',
        ),
    ]
